theme: jekyll-theme-hacker
show_downloads: false

title: demo - rzning.com
description: Some online sample
author: Rzning
email: rzning@outlook.com
github_username: rzning

encoding: utf-8
timezone: Asia/Shanghai

collections:
  samples:
    output: true
    # pertty: false
    permalink: /:path

exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - README.md
  - CNAME